### PR TITLE
Monster pull request with changes from the last 5 years

### PR DESCRIPTION
**Pull request by evanmiller**
Greetings all,

After 20 years of development and maintenance of this project by @brianb, to whom we are all grateful for sharing this code base, he has agreed to let me take over duties as project maintainer of MDB Tools. I use the project regularly and will do my best to keep it up to date going forward.

This pull request reflects the collective efforts of @cyberemissary, @nyalldawson, myself, and several others to fix bugs and security issues and also to add a few new features. The key areas of improvements are:

* Improved bounds checking in many places
* Improved ODBC support
* Improved support for newer Access files
* Added bulk insert support
* Added fuzz testing support
* Added continuous integration with Travis and Appveyor
* New in-memory file API
* Thread safety
* GLib is now optional
* Many bug fixes

I still need to update the README but I am opening this PR for general comments and questions before merging it in to the main repository. Going forward, the plan is to use the new `dev` branch for active development and `master` for stable releases. I hope to roll out an official release with the cumulative updates sometime within the next 2 months. So if you've been sitting on a patch, please open a pull request (or add a "bump" to your existing PR) and I will take a look at it.

Thanks for your patience while I sort through the backlog of open issues and pull requests. Here's to many more productive years of MDB Tools! 🍻

### CODE REVIEW

**Comment by nyalldawson** [comment]
Wow, great news! Thanks for your hard work here!

**Comment by davidhicks** [comment]
@evanmiller Can you also please pull [Fix typo in gmdb2 table_export.c preventing build](https://github.com/davidhicks/mdbtools/commit/48f19d05deed259c273e62e6bfb825946cac54b2) which resolves a typo impacting build of the gmdb2 functionality that I proposed back in 2014 in #55

**Comment by evanmiller** [comment]
@davidhicks Thanks for the suggestion. I've pushed a change which follows the tip in the code comments – eliminating the duplicate code.

**Comment by rhurlin** [comment]
For the case, that a new release of mdbtools/mdbtools is in preparation:

The versions on https://github.com/cyberemissary/mdbtools/releases reached 0.8.2 and some distros changed to that repo and updated on version 0.8.2 (FreeBSD and some Linuxes). 

I would like to suggest, that the next version of mdbtools should be at least version 0.8.3 or greater. What do you thinks about it?

**Comment by evanmiller** [comment]
@rhurlin Good suggestion. Yes we will avoid version conflicts with the cyberemissary releases. Since some distros use them, perhaps I will pull them in and make those 0.8 releases "official" after-the-fact.

**Comment by evanmiller** [comment]
TODO update libtool's `version-info` to reflect API breakage.

**Pull request merged**
