### PR TITLE
Add support for custom create table statements and table name normali…

### PR DESCRIPTION
**Pull request by doraemoncito**
…sation.

### CODE REVIEW

**Comment by evanmiller** [comment]
Thanks for the pull request. To assist with analysis / discussion, I'd suggest breaking this up into three separate PRs (one for the .gitignore, one for create tables, one for table name normalization).

The case transformation functions will need to be UTF-8 compatible. I suggest looking at [g_utf8_strup](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-utf8-strup) and friends.

**Comment by doraemoncito** [comment]
Added a separate PR (<https://github.com/mdbtools/mdbtools/pull/320>) for the .gitignore change as suggested.

**Comment by doraemoncito** [comment]
Added a separate PR (https://github.com/mdbtools/mdbtools/pull/321) for the customised per-database create table statements change as suggested.

**Comment by doraemoncito** [comment]
Rebased branch to include the latest changes from develop and added a separate PR (https://github.com/mdbtools/mdbtools/pull/322) for the name normalisation change as suggested.  I.e. names are exported consistently in lowercase in PostgreSQL.

**Pull request closed without merging**
