### PR TITLE
Added setlocale to support umlauts in mdb-schema 

### PR DESCRIPTION
**Pull request by chrgm**
This should be a fix for #234. 
I don't know if the change in `include/mdbtools.h` messed something up as I don't know too much about xlocale.

### CODE REVIEW

**Comment by evanmiller** [comment]
Thanks for the contribution. The change to the header file is fine.

Please add a test case so I can confirm that your proposed fix works across all platforms.

I assume that the other CLI tools will need a similar patch?

**Comment by chrgm** [comment]
I will create a test. 
Are there any tips how to create a new table without MS Access? I don't have access to an installation so I don't know yet how to create a table with umlauts now.

**Comment by evanmiller** [comment]
There is some experimental writing code in MDB Tools but to be honest I am not sure what it supports.

Maybe Jackcess can help? https://jackcess.sourceforge.io

**Comment by chrgm** [comment]
I figured out the umlaute just affects the locale when at least the `postgres` option is set.

**Comment by evanmiller** [comment]
Thanks. It looks like the tests are passing without the new test file, which shouldn't be the case. Probably mdb-schema should fail or at least return an error code if the requested table is not found. I will look into it.

**Comment by evanmiller** [comment]
Hi, I've merged your test data and updated the `mdb-schema` code to return an error if the requested table is not found. Please merge in the latest changes from `dev` and push to your branch so that the CI tests can verify your pull request properly.

**Comment by evanmiller** [comment]
Hi, the Umsätze table is not being located properly in the Windows build (expand the "Test" section and scroll to the bottom):

https://github.com/mdbtools/mdbtools/runs/1693803219?check_suite_focus=true

**Comment by evanmiller** [comment]
Here's some more information on command line encodings:

https://stackoverflow.com/questions/5408730/what-is-the-encoding-of-argv

Probably more than you want to chew, but here's a recent PR (from another project that I manage) supporting Unicode file paths on Windows:

https://github.com/WizardMac/ReadStat/pull/216

Overall it's not a very pleasant situation with potentially different encodings for the filenames and for the typed in arguments. I'm not sure exactly what `setlocale` is changing here and a more tailored solution may be possible.

**Comment by chrgm** [comment]
As I don't have a windows machine I don't know how I can test that here. If you have any ideas let me know and I will have a look on it. Push it every time to github for every test wouldn't really productive.

I'm not very familiar with the whole locale stuff especially when it's cross platform but would want to help if I find a not to complicated way to test it with windows.

**Comment by evanmiller** [comment]
If you don't have a Windows machine then pushing to GitHub (on a separate branch) is probably your best bet for testing. The tests should run automatically on your fork under the Actions tab.

I've made a change so that the test suite will show failure if any individual test fails. So you may want to merge in `dev` again.

I'd be curious to know if any of the platforms work without the proposed `setlocale` change. For example, it seems to work okay on my Mac without calling setlocale. [This page](https://tecnocode.co.uk/2011/08/27/character-encoding-and-locales/) indicates that GLib will automatically handle conversion to UTF-8.

Which platform are you using locally? Are you compiling with GLib or not?

**Comment by evanmiller** [comment]
Based on this test run:

https://github.com/evanmiller/mdbtools/runs/1697599486?check_suite_focus=true

It looks like the original issue crops up with GLib's option parser. There's more information about that here:

https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html#glib-Commandline-option-parser.description

GLib expects `setlocale` to be called in order to reliably return UTF-8 strings. Our "fake GLib" ignores encodings and seems to work fine on UTF-8 systems but not others (Windows). In the documentation there's no indication about why `setlocale` needs to be called or with which arguments, but it seems you discovered that calling it with "" does the trick - apparently it tells GLib to use the native locale to decode the arguments.

Reading the documentation, it looks like we should be treating some options as ARG_FILENAME rather than ARG_STRING, since these are decoded differently.

So a complete solution would call `setlocale` so that real GLib works correctly, and also fix the fake GLib to convert string arguments to UTF-8 regardless of native locale.

**Comment by evanmiller** [comment]
My proposed fix is here:

https://github.com/mdbtools/mdbtools/tree/utf8-cli-test

**Comment by evanmiller** [comment]
Hi, this fix ended up being much more complicated than I anticipated. I am closing this pull request in favor of #237 which includes complete support for converting command-line arguments to UTF-8, regardless of locale. Please test that code and let me know if it works for you.

**Pull request closed without merging**
