### PR TITLE
Don't link odbc code with -lfl

### PR DESCRIPTION
**Pull request by czarkoff**
Should fix issue #47.

### CODE REVIEW

**Comment by LukeShu** [comment]
I'm not sure if it is preventing it from building, but `@LEXLIB@` should also be removed from `src/util/Makefile.am` and `src/gmdb2/Makefile.am`, not just `src/odbc/Makefile.am`.

**Comment by czarkoff** [comment]
@LukeShu: nope, these two geniunely need `@LEXLIB@` because that are utils and gmdb2 where linking bineries against lex-generated code takes place.

**Comment by LukeShu** [comment]
Using lex-generated code doesn't mean you need to link against `@LEXLIB@`; only specific patterns of usage require `@LEXLIB@` (mostly just using `yywrap`, but not providing a custom implementation).

None of the code in mdbtools uses any of those features.  Prior to 2001, the `@LEXLIB@` `yywrap` was used, but on [2001-09-29](https://github.com/brianb/mdbtools/commit/ea8fd2a6ba6fe25095747a203cbfe803d1bb1563#diff-02f0b547c2779d25cff89672135f20e3R7) a custom `yywrap` was added specifically to avoid needing to link against `@LEXLIB@`.

**Comment by evanmiller** [comment]
Included in #162, thanks for the contribution!

**Pull request closed without merging**
