### PR TITLE
Hacking

### PR DESCRIPTION
**Pull request by pedromorgan**
So this is WIP.. on the HACKING.md page and linking it formatting etc  and its getting quite long really

so my suggestion is to split hacking out into seperate pages.. proper .dox

- overview
- pages
- tables + cols
- indexes
- etc

What you think @evanmiller ?

### CODE REVIEW

**Comment by evanmiller** [comment]
Well, the HACKING file is special because it is linked from several places, including the Library of Congress!

https://www.loc.gov/preservation/digital/formats/fdd/fdd000462.shtml

So I'd prefer to keep it as one big file. I'm OK with moving to Markdown but we should add a reference from the old text file so that the links still work.

**Comment by pedromorgan** [comment]
Ping me at https://gitter.im/mdb-tools/community# if around.. probably a quick chat better that issues...

**Comment by pedromorgan** [comment]
@evanmiller here a preview of the patch https://mdbtools.gitlab.io/mdbtools/hacking.html (will squash and maybe push myself to dev ?)

**Comment by evanmiller** [comment]
This is looking good. My only concern is that the HACKING.md file has markup that is not rendered by GitHub (\warning, \ref, anchors, etc). So we will want to decide on a canonical URL for viewing the file and link appropriately.

**Comment by pedromorgan** [comment]
its one or other

**Pull request closed without merging**
