### PR TITLE
Add support for <> SQL operator

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by evanmiller** [comment]
Very nice. Please update the mdb-sql man page as well.

**Comment by nyalldawson** [comment]
@evanmiller 
> Please update the mdb-sql man page as well.

Hmm - strangely enough, the man page already incorrectly states there's support for "<>"!

**Comment by nyalldawson** [comment]
Can you explain the build failure in CIFuzz?

**Comment by evanmiller** [comment]
The CIFuzz looks like an issue with the recent HAVE_ICONV work, unrelated to your change.

**Comment by nyalldawson** [comment]
Thanks @evanmiller , appreciate your hard work here!

I have a related question: it makes me nervous adding things like this with no tests to accompany it. I'd be more than happy to start chipping away at a test suite for mdbtools, but I'd first like your thoughts on this. Have you previously given this any thought? If so, is there a preferred setup you'd like to see used for tests? (eg. python based tests using unittest, compiled tests using google test framework or equivalent, or ...?)

**Comment by evanmiller** [comment]
@nyalldawson Haven't given it any thought but a test suite would be welcome. I think the choice of tech will depend on the overall strategy (unit tests vs SQL/ODBC tests vs CLI tests). Feel free to open an issue to discuss.

**Pull request merged**
