### PR TITLE
ODBC garbage collection

### PR DESCRIPTION
**Pull request by evanmiller**
I'm creating pull requests out of the stale branches on the original repository. Please leave a comment if you find this change useful (or problematic).

### CODE REVIEW

**Comment by evanmiller** [comment]
I will note that this commit uses global variables and may need additional work to ensure thread safety. The benefit of the commit is somewhat marginal IMO as it seems designed to work around memory management bugs in ODBC libraries.

**Comment by rogerswb** [comment]
It's been quite a while since I touched any of this code, but if I remember correctly, these changes were less about working around memory management bugs, and more about appropriate memory housekeeping. The driver is meant to be responsible for cleanup of any memory allocated during its use. In particular, memory leaks could occur when the driver was incorrectly used or functions were called in the incorrect order. In cases where the driver is used for a single import from a database, these leaks are negligible, but I was also using this driver in a continuously running process, so any leaks whatsoever were problematic.

**Comment by evanmiller** [comment]
@rogerswb Thanks for the clarification. It does sound useful if you were seeing memory leaks in a long running process. I will leave this open for now in case anyone wants to merge and test it.

My main concern with the patch, for anyone reading this, would be preventing race conditions on the global `handles` object. We've done a lot of work to ensure thread safety in the rest of the ODBC code and I'd like to keep it reliably re-entrant.

One possible strategy would be ensuring that freeing the environment frees all of the associated statement and parameter handles. Then you only need to worry about managing the environment handles correctly.

**Comment by evanmiller** [comment]
After further research, I believe that this `odbc_garbagec` branch was superseded by the following commit a month later: https://github.com/mdbtools/mdbtools/commit/66b87caf262a5c8fc1ab69d8367c7742ad48973d

Closing this pull request. If anyone encounters remaining memory management bugs in the ODBC driver, please open a new issue. I will plan to delete this branch at some point in the not-too-distant future.

**Pull request closed without merging**
