### PR TITLE
sql: sql: allow double quoted (") database names

### PR DESCRIPTION
**Pull request by Bob620**
reinstate #289

### CODE REVIEW

**Comment by evanmiller** [comment]
Hi, thanks for the contribution. This should probably be 2 separate pull requests (one dealing with the space issue, the other dealing with the quote issue). The proper solution for the space issue is probably to just rip out all the HAVE_WORDEXP stuff. This will involve modifying the `configure.ac` file, which might be more than you're comfortable with.

I will be happy to merge in a simple pull request with just the quote issue addressed. I will leave this issue open for now.

**Comment by Bob620** [comment]
I can understand it being separated into multiple pull requests, as I was unsure about how to handle the HAVE_WORDEXP stuff and tbh I'm not sure how the cast from db_name -> db_namep even breaks things, I was just testing various solutions and used what little C knowledge I had.

I am not comfortable working that far into the repo as I have no experience with it, and am not sure how much would even need to change nor do I have experience with `configure.ac` or `wordexp`.

**Comment by evanmiller** [comment]
@Bob620 Not a problem at all. I went ahead and merged your no-space PR. I'll plant open a new PR for you to test that addresses the space issue.

**Comment by evanmiller** [comment]
Superseded by #293

**Pull request closed without merging**
